mail-validator/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post '/' => 'home#check_email', as: :validate_email
end

mail-validator/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

mail-validator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

mail-validator/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def check_email
    @result = validate
    render 'index'
  end

  private
  def validate
    EmailDomainValidationService.new(email: params['/'][:email]).response
  end

end

mail-validator/app/helpers/application_helper.rb
module ApplicationHelper
end

mail-validator/app/helpers/home_helper.rb
module HomeHelper
end

mail-validator/app/views/home/_messages.html.erb
<% if obj["format_valid"] && obj["smtp_check"] %>
<h1 style="color: darkgreen"> This Email is valid <%= ',but it\s disposable' if obj["disposable"] %></h1>
<% else %>
<h1 style="color: darkred"> Invalid Email Domain<%= ', Did you mean ?' if obj["did_you_mean"] != "" %></h1>
  <h3> <%= obj["did_you_mean"] if obj["did_you_mean"] != "" %> </h3>
<% end %>

mail-validator/app/views/home/index.html.erb
<div class="login">
  <h1>Check Email</h1>
  <%= form_for validate_email_path do |f| %>
    <%= f.email_field :email, placeholder: 'Email Address' %>
    <div style="padding-top: 10%"></div>
    <%= f.button 'Check domain validation', type: 'submit', class: 'btn btn-primary btn-block btn-large' %>
  <% end %>
  <div style="padding-top: 10%"></div>
  <% if @result %>
    <%= render 'messages', obj: @result  %>
  <% end %>
</div>

mail-validator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailValidator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
  </head>

  <body>
   <%= yield %>
  </body>
</html>